#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include the bindings generated by build.rs
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Export the safe wrapper module.
pub mod wrappers;

// The C struct `VL53L5CX_Configuration` does not derive Default.
// We need to implement it manually so that it can be easily initialized.
impl Default for VL53L5CX_Configuration {
    fn default() -> Self {
        // Safe way to create a zero-initialized struct.
        unsafe { core::mem::zeroed() }
    }
}